title: Apuntes de Física IV
author: Enrique Conejero Jarque, Luis Plaja Rustein, Javier Rodríguez Vázquez de Aldana
copyright: "2026"
logo: "_static/logo.png"
language: es
exclude_patterns: ["_build", "Thumbs.db", ".DS_Store", "**.ipynb_checkpoints", "_build_*", "en/", "temp_build_*", "latex_templates*", "_TRASH*"]
execute:
  execute_notebooks: off
parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - linkify
    - amsmath
  use_download_button: true
  extra_navbar: |
    <div style="margin-top: 10px; font-size: 0.8em; color: #666;">
      Powered by <a href="https://jupyterbook.org">Jupyter Book</a>
    </div>
html_theme_options:
  icon_links: []
sphinx:
  extra_extensions:
    - sphinx_thebe
    - sphinxcontrib.bibtex
    - sphinx_kroki
    - sphinx.ext.mathjax
  config:
    html_show_copyright: false
    numfig: true
    numfig_secnum_depth: 1
    math_number_all: true
    math_numfig: true
    math_eqref_format: "({number})"
    numfig_format:
      figure: "Figura %s"
      table: "Tabla %s"
      code-block: "Ejemplo %s"
      equation: "Ecuación %s"
    suppress_warnings:
      - bibtex.duplicate_citation
    html_js_files:
      - custom.js
    bibtex_bibfiles:
      - _static/references.bib
    thebe_config:
      always_load: false
      repository_url: https://github.com/binder-examples/jupyter-stacks-datascience
      repository_branch: master
      selector: ".thebe,.cell"
      selector_input: "pre"
      selector_output: ".output, .cell_output"
html:
  extra_footer: |
    <p>Construido con una versión modificada de <a href="https://teachbooks.io/">TeachBooks</a>, <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="license noopone noreferrer">CC BY 4.0<img style=\"height:22px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/cc.svg\" alt=\"\"><img style=\"height:22px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/by.svg\" alt=\"\"></a></p>
latex_docclass:
  book: jupyterBook
latex:
  latex_engine: xelatex
  options: "spanish"
  subtitle: "Oscilaciones, ondas, óptica y física cuántica"
  header_title: Apuntes de Física IV
  institution: "Universidad de Salamanca"
  edition: "1ª Edición"
  cover_logo: "_static/usal_logo.png"
  preamble: |
    \usepackage[spanish]{babel}
    \selectlanguage{spanish}
    \usepackage{amsmath}
    \numberwithin{equation}{section}
    \numberwithin{figure}{section}
